Repository NikRam822/TatMobileAnalyzer, pull requests merged in 2024-04, with the labels that each got.

#29 Features/read patch for period
  pom.xml
  src/main/java/com/example/TatMobileAnalyzer/controllers/StatisticController.java
  src/main/java/com/example/TatMobileAnalyzer/services/LocFilesService.java
  src/main/java/com/example/TatMobileAnalyzer/services/PatchScanService.java
  src/main/java/com/example/TatMobileAnalyzer/services/impl/LocFilesServiceImpl.java
  src/main/java/com/example/TatMobileAnalyzer/services/impl/PatchReader.java
  src/main/java/com/example/TatMobileAnalyzer/services/impl/PatchScanServiceImpl.java
  src/main/java/com/example/TatMobileAnalyzer/utils/DateUtils.java
Labels: feature

#30 Create contribution stats per file getter
  src/main/java/com/example/TatMobileAnalyzer/controllers/StatisticController.java
  src/main/java/com/example/TatMobileAnalyzer/services/FileStatService.java
  src/main/java/com/example/TatMobileAnalyzer/services/impl/FileStatServiceImpl.java
  src/main/java/com/example/TatMobileAnalyzer/utils/MapToCsvConverter.java
Labels: feature

#37 Repository and project review 1
  README.md
  docs/README.md
  docs/reviews.md
Labels: enhancement

#43 Add sprint rules
  docs/WORKFLOW.md
Labels: documentation

#45 Add base for filter solution
  src/main/java/com/example/TatMobileAnalyzer/controllers/FilterController.java
  src/main/java/com/example/TatMobileAnalyzer/controllers/ProjectController.java
  src/main/java/com/example/TatMobileAnalyzer/controllers/StatisticController.java
  src/main/java/com/example/TatMobileAnalyzer/dto/FilterDto.java
  src/main/java/com/example/TatMobileAnalyzer/dto/ProjectDto.java
  src/main/java/com/example/TatMobileAnalyzer/model/Filter.java
  src/main/java/com/example/TatMobileAnalyzer/model/Project.java
  src/main/java/com/example/TatMobileAnalyzer/repository/FilterRepository.java
  src/main/java/com/example/TatMobileAnalyzer/repository/ProjectRepository.java
  src/main/java/com/example/TatMobileAnalyzer/services/FilterService.java
  src/main/java/com/example/TatMobileAnalyzer/services/PatchScanService.java
  src/main/java/com/example/TatMobileAnalyzer/services/ProjectService.java
  src/main/java/com/example/TatMobileAnalyzer/services/impl/FilterServiceImpl.java
  src/main/java/com/example/TatMobileAnalyzer/services/impl/PatchScanServiceImpl.java
  src/main/java/com/example/TatMobileAnalyzer/services/impl/ProjectServiceImpl.java
Labels: enhancement, feature
